# Generated by Django 4.1 on 2022-09-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_raça'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acompanhamento_animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('peso', models.CharField(max_length=100)),
                ('id_acompanhamento', models.CharField(max_length=100)),
                ('data', models.CharField(max_length=100)),
                ('altura', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Espécie',
        ),
    ]
