# Generated by Django 4.1 on 2022-09-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_acompanhamento_animal_delete_espécie'),
    ]

    operations = [
        migrations.AddField(
            model_name='acompanhamento_animal',
            name='ficha_clinica',
            field=models.URLField(blank=True, null=True),
        ),
    ]
