# Generated by Django 4.1 on 2022-09-21 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_acompanhamento_animal_ficha_clinica'),
    ]

    operations = [
        migrations.CreateModel(
            name='adocao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_adocao', models.CharField(max_length=100)),
                ('data_adocao', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cruzamento', models.CharField(max_length=100)),
                ('porte', models.CharField(max_length=100)),
                ('descricao', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=100)),
                ('id_animal', models.CharField(max_length=100)),
                ('idade', models.CharField(max_length=100)),
                ('url_foto_animal', models.URLField(blank=True, null=True)),
                ('cod_doacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='doacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('data_inicio_doacao', models.CharField(max_length=100)),
                ('data_fim_doacao', models.CharField(max_length=100)),
                ('cod_doacao', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
            ],
        ),
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=13)),
                ('senha', models.CharField(max_length=100)),
                ('confirmacao_senha', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('url_foto_usuario', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='raça',
            name='site',
        ),
    ]
