# Generated by Django 4.1 on 2022-10-25 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_adocao_animal_doacao_especie_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acompanhamento_animal',
            name='id_acompanhamento',
        ),
        migrations.RemoveField(
            model_name='adocao',
            name='id_adocao',
        ),
        migrations.RemoveField(
            model_name='animal',
            name='id_animal',
        ),
        migrations.RemoveField(
            model_name='doacao',
            name='cod_doacao',
        ),
    ]
