# Generated by Django 4.1 on 2022-10-25 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_acompanhamento_animal_id_acompanhamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animal',
            name='cod_doacao',
        ),
    ]
