# Generated by Django 4.1 on 2022-10-25 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_animal_cod_doacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='especie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='animal', to='core.especie'),
            preserve_default=False,
        ),
    ]
