# Generated by Django 4.1 on 2022-10-25 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_animal_especie'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='raca',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='animal', to='core.raça'),
            preserve_default=False,
        ),
    ]
